apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: ewallet
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: gbrn7/ewallet-notification:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 7003
          envFrom:
            - configMapRef:
                name: ewallet-config
            - secretRef:
                name: ewallet-secret
          env:
            - name: APP_NAME
              value: "ewallet-notification"
            - name: PORT
              value: "8083"
            - name: GRPC_PORT
              value: "7003"
            - name: DB_NAME
              value: "ewallet_notification"
