apiVersion: apps/v1
kind: Service
metadata:
  name: notification
spec:
  selector: 
    matchLabels:
      app: notification
    type: NodePort 
      ports:
        - protocol: TCP
          name: grpc
          port: 7003
          targetPort: 7003 #HTTP
          nodePort: 30005
        
