apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: ewallet
  labels:
    app: transaction
spec:
  type: ClusterIP
  selector:
    app: transaction
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8082
