apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
  namespace: ewallet
  labels:
    app: ums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
        - name: ums
          image: gbrn7/ewallet-ums:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 7000
          envFrom:
            - configMapRef:
                name: ewallet-config
            - secretRef:
                name: ewallet-secret
          env:
            - name: APP_NAME
              value: "ewallet-ums"
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "7000"
            - name: DB_NAME
              value: "ewallet_ums"
