apiVersion: v1
kind: Service
metadata:
  name: ums
  namespace: ewallet
  labels:
    app: ums
spec:
  type: ClusterIP
  selector:
    app: ums
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: grpc
      port: 7000
      targetPort: 7000
